const rooms={mehfil:{name:'Mehfil',kicker:'amber light',description:'Ghazals, old classics, and the warmth of a room still awake.',tracks:[['Gulon Mein Rang Bhare','Mehdi Hassan','5:42'],['Honthon Se Chhoo Lo Tum','Jagjit Singh','4:57'],['Woh Shaam Kuch Ajeeb Thi','Kishore Kumar','4:43']]},halleriya:{name:'Halleriya',kicker:'blue hour',description:'Late-night songs for when the city has softened around you.',tracks:[['Iktara','Kavita Seth','3:15'],['Kasoor','Prateek Kuhad','3:17'],['Baarishein','Anuv Jain','3:27']]},nishabd:{name:'Nishabd',kicker:'low words',description:'A calm desk, an open window, and enough quiet to begin.',tracks:[['Near Light','Ólafur Arnalds','3:28'],['Ambre','Nils Frahm','3:42'],['A Walk','Tycho','5:17']]},baarish:{name:'Baarish',kicker:'rain on glass',description:'Songs for a wet window and the thoughts that arrive with it.',tracks:[['Rim Jhim Gire Saawan','Kishore Kumar','3:14'],['Bheegi Bheegi Raaton Mein','Lata Mangeshkar','3:52'],['Rainy Day','Anuv Jain','3:16']]},subah:{name:'Subah',kicker:'first light',description:'Gentle songs for paper, warm tea, and an unhurried morning.',tracks:[['Khaabon Ke Parinday','Alyssa Mendonsa','3:12'],['Bloom','The Paper Kites','3:31'],['Morning Has Broken','Cat Stevens','3:20']]},safar:{name:'Safar',kicker:'open road',description:'The road is long enough for another song.',tracks:[['Ilahi','Arijit Singh','3:48'],['Phir Se Ud Chala','Mohit Chauhan','4:28'],['Home','Edward Sharpe','5:05']]}};
let room='mehfil',trackIndex=0,playing=false,elapsed=0,timer,ambience='subtle';const $=id=>document.getElementById(id);const secs=t=>{const[a,b]=t.split(':').map(Number);return a*60+b};const stamp=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
function renderRooms(){$('room-grid').innerHTML=Object.entries(rooms).map(([id,item],i)=>`<button type="button" data-room="${id}" class="room ${id===room?'is-active':''}"><small>0${i+1}</small><strong>${item.name}</strong><span>${item.kicker}</span></button>`).join('')}
function updateProgress(){const input=$('progress');input.style.setProperty('--progress',`${elapsed/input.max*100}%`);$('elapsed').textContent=stamp(elapsed)}
function updateTrack(){const current=rooms[room],track=current.tracks[trackIndex],duration=secs(track[2]);$('room-description').textContent=current.description;$('label-room').textContent=current.name.toUpperCase();$('label-song').textContent=track[0];$('label-artist').textContent=track[1];$('now-kicker').textContent=`${current.name.toUpperCase()} · ${current.kicker.toUpperCase()}`;$('song-title').textContent=track[0];$('artist').textContent=track[1];$('duration').textContent=track[2];$('progress').max=duration;elapsed=0;$('progress').value=0;updateProgress()}
function setPlaying(value){playing=value;clearInterval(timer);$('record').classList.toggle('is-playing',playing);$('needle').classList.toggle('is-playing',playing);$('play').textContent=playing?'Pause':'Play';$('record').setAttribute('aria-label',`${playing?'Pause':'Play'} ${rooms[room].tracks[trackIndex][0]}`);if(playing)timer=setInterval(()=>{elapsed++;if(elapsed>=Number($('progress').max)){trackIndex=(trackIndex+1)%rooms[room].tracks.length;updateTrack()}else{$('progress').value=elapsed;updateProgress()}},1000)}
function chooseRoom(next){room=next;trackIndex=0;document.body.dataset.room=room;renderRooms();updateTrack();show(`${rooms[room].name} · ${rooms[room].kicker}`)}
function show(message){const toast=$('toast');toast.textContent=message;toast.classList.add('is-visible');setTimeout(()=>toast.classList.remove('is-visible'),1800)}
$('record').onclick=()=>setPlaying(!playing);$('play').onclick=()=>setPlaying(!playing);$('previous').onclick=()=>{trackIndex=(trackIndex+rooms[room].tracks.length-1)%rooms[room].tracks.length;updateTrack()};$('next').onclick=()=>{trackIndex=(trackIndex+1)%rooms[room].tracks.length;updateTrack()};$('progress').oninput=e=>{elapsed=Number(e.target.value);updateProgress()};$('room-grid').onclick=e=>{const button=e.target.closest('[data-room]');if(button)chooseRoom(button.dataset.room)};$('ambience').onclick=()=>{ambience={off:'subtle',subtle:'present',present:'off'}[ambience];$('ambience').innerHTML=`Ambience <span>${ambience}</span>`;show(ambience==='off'?'The room is quiet':ambience==='present'?'The room is a little closer':'The room is softly present')};renderRooms();updateTrack();
